# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"path": "00_core.ipynb",
         "df": "00_core.ipynb",
         "cat_names": "00_core.ipynb",
         "cont_names": "00_core.ipynb",
         "get_emb_sz": "00_core.ipynb",
         "emb_sz_rule": "00_core.ipynb",
         "splits": "00_core.ipynb",
         "procs": "00_core.ipynb",
         "y_names": "00_core.ipynb",
         "y_block": "00_core.ipynb",
         "to": "00_core.ipynb",
         "dls": "00_core.ipynb",
         "emb_szs": "00_core.ipynb",
         "init_glu_linear": "00_core.ipynb",
         "init_non_glu_linear": "00_core.ipynb",
         "TNEMbedding": "00_core.ipynb",
         "GBN": "00_core.ipynb",
         "GLUBlock": "00_core.ipynb",
         "FeatureTransformer": "00_core.ipynb",
         "SparsemaxFunction": "00_core.ipynb",
         "Sparsemax": "00_core.ipynb",
         "sparsemax": "00_core.ipynb",
         "AttentiveTransformer": "00_core.ipynb",
         "TabNetEncoder": "00_core.ipynb",
         "TabNet": "00_core.ipynb",
         "TabNetLoss": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://numb3r33.github.io/tabnet/"

git_url = "https://github.com/numb3r33/tabnet/tree/main/"

def custom_doc_links(name): return None
